---
services:
  user-service:
    image: user-service
    build:
      context: ./
      dockerfile: $PWD/Dockerfile
    container_name: user-service
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DIALECT=${DB_DIALECT}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_HOST=${REDIS_HOST}
    networks:
      user_network:
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:3000

  postgres:
    image: postgres:latest
    container_name: postgres-user
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      user_network:
    ports:
      - 5446:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    container_name: redis-user
    networks:
      user_network:
    ports:
      - 6388:6379

networks:
  user_network:
    name: user_network
    driver: bridge
    